---
definitions:
  DatasetChecksums:
    type: object
    properties:
      anchors:
        type: string
        description: "Checksum value for the anchors dataset"
        example: ab0a4c3fc5dcf9e6404c45eaad1eb463b38673a4936ab3f80e7dcdbf8130dee5
      w2vfiltered:
        type: string
        description: "Checksum value for the w2vfiltered dataset"
        example: 59cb88563ca2e0d1992d71d28921f04e902880a9bc9d03081360cbef69fa229c
      redirects:
        type: string
        description: "Checksum value for the redirects dataset"
        example: 56e8089b9d930b4ff77dbc9495c6a2e67c48d8d8a023f9b148e3bbfe5a98665f
      pageids:
        type: string
        description: "Checksum value for the pageids dataset"
        example: 05391e1229aefc087c5076bea2042cddcc0d23bded0f6262cc474898a954c96e
      model:
        type: string
        description: "Checksum value for the model dataset"
        example: c25a9fb36577a272dd7ca101655d6169bf8a86dbfb1edce7c9b6ee445dec8e71
  Meta:
    type: object
    properties:
      format_version:
        type: integer
        description: "Format version for the response"
        example: 1
      application_version:
        type: string
        description: "Git commit hash associated with the application that generated the response"
        example: 2fe11bb
      dataset_checksums:
        $ref: '#/definitions/DatasetChecksums'
  LinkRecommendationSet:
    type: object
    properties:
      meta:
        $ref: '#/definitions/Meta'
      links:
        type: array
        description: 'Array of link recommendation objects'
        items:
          $ref: '#/definitions/LinkRecommendation'
      links_count:
        type: integer
        description: 'Number of link recommendations'
        example: 5
      page_title:
        type: string
        description: 'Wiki page title'
        example: Lipsko
      pageid:
        type: integer
        description: 'Page identifier'
        example: 23151
      revid:
        type: integer
        description: 'Revision identifier'
        example: 25567649
  LinkRecommendation:
    type: object
    properties:
      link_text:
        type: string
        description: 'Phrase to link in the article text'
        example: 'povrchových dolech'
      wikitext_offset:
        type: integer
        description: 'Character offset describing where the anchor begins'
        example: 2379
      context_before:
        type: string
        description: 'Characters immediately preceding the link text, in plain text. May include spaces, punctuation, and partial words'
        example: ' v '
      context_after:
        type: string
        description: 'Characters immediately succeeding the link text, in plain text. May include spaces, punctuation, and partial words'
        example: ', které js'
      link_target:
        type: string
        description: 'Article title to link to'
        example: 'Povrchový důl'
      match_index:
        type: integer
        description: >
          0-based index of the link anchor within the list of matches when searching for the phrase to link
          within simple wikitext (top-level wikitext that's not part of any kind of wikitext construct)
        example: 0
      score:
        type: number
        description: 'Probability score that the link should be added'
        example: 0.5150544047355652
      link_index:
        type: integer
        description: "0-based index of the link recommendation within all link recommendations, sorted by wikitext offset"
        example: 1
info:
  description: >
    Link Recommendation API suggests places in an article where a link could be added.
    This helps guide editors in the important work of creating connections between different topics.
    For more information, see the [wiki page](https://www.mediawiki.org/wiki/Special:MyLanguage/Link_Recommendation_API).
  title: Wikimedia Link Recommendation API
  version: 1.0.0
paths:
  "/v1/linkrecommendations/{project}/{domain}/{page_title}":
    post:
      summary: Get link recommendations for revision
      description: Given a specific page source, get a set of possible links that can be added to improve an article on Wikipedia.
      x-monitor: true
      x-amples:
        - request:
            params:
              project: wikipedia
              domain: cs
              page_title: Lipsko
            headers:
              Content-Type: "application/json"
            body:
              pageid: 23151
              revid: 25567649
              wikitext: "{{Infobox - sídlo světa..."
            query:
              max_recommendations: 1
              threshold: 0.1
              language_code: cs
            response:
              status: 200
              body:
                links_count: 1
                page_title: "Lipsko"
                pageid: 23151
                revid: 25567649
                meta:
                  format_version: 1
      parameters:
        - name: project
          type: string
          in: path
          description: 'Project name. Only "wikipedia" is supported'
          required: true
        - name: domain
          type: string
          description: 'Project subdomain, usually the language code. For example: "en" for English Wikipedia. The majority of [Wikipedia subdomains](https://meta.wikimedia.org/wiki/Special:SiteMatrix) are supported. Unsupported subdomains return a 404 error'
          in: path
          required: true
        - name: page_title
          type: string
          description: 'Wiki page title'
          in: path
          required: true
        - name: language_code
          type: string
          description: 'Language code (ISO-639) to use with the request. Defaults to the domain parameter'
          in: query
          required: false
        - name: threshold
          in: query
          required: false
          type: number
          default: 0.5
          description: 'Number between 0 and 1 for the threshold to use'
        - name: sections_to_exclude
          in: query
          required: false
          schema:
            items:
              type: string
            type: array
          description: 'Sections to exclude from link suggestion generation. Exact match is used. To exclude the lead section, use %LEAD%'
        - name: max_recommendations
          in: query
          required: false
          type: number
          default: 15
          description: 'Maximum number of recommendations to return'
        - name: body
          in: body
          required: true
          schema:
            id: Input
            required:
              - wikitext
              - revid
              - pageid
            properties:
              wikitext:
                type: string
                description: 'Raw wikitext of the page'
              revid:
                type: integer
                description: 'Revision identifier'
              pageid:
                type: integer
                description: 'Page identifier'
              sections_to_exclude:
                type: array
                items:
                  type: string
                description: 'Sections to exclude from link suggestion generation. Exact match is used. To exclude the lead section, use %LEAD%'
      responses:
        200:
          description: 'Success: Page found'
          schema:
            $ref: '#/definitions/LinkRecommendationSet'
    get:
      summary: Get link recommendations
      description: Returns a set of possible links that can be added to improve an article on Wikipedia.
      x-monitor: true
      x-amples:
        - request:
            params:
              project: wikipedia
              domain: cs
              page_title: Lipsko
            query:
              max_recommendations: 1
              threshold: 0.1
              language_code: cs
            response:
              status: 200
              meta:
                format_version: 1
              body:
                page_title: "Lipsko"
      parameters:
      - name: project
        type: string
        in: path
        description: 'Project name. Only "wikipedia" is supported'
        required: true
      - name: domain
        type: string
        description: 'Project subdomain, usually the language code. For example: "en" for English Wikipedia. The majority of [Wikipedia subdomains](https://meta.wikimedia.org/wiki/Special:SiteMatrix) are supported. Unsupported subdomains return a 404 error.'
        in: path
        required: true
      - name: page_title
        in: path
        required: true
        type: string
        description: 'Wiki page title'
      - name: language_code
        type: string
        description: 'Language code (ISO-639) to use with the request. Defaults to the domain parameter'
        in: query
        required: false
      - name: revision
        in: query
        required: false
        type: number
        description: 'Revision identifier. Defaults to the latest revision'
      - name: threshold
        in: query
        required: false
        type: number
        default: 0.5
        description: 'Number between 0 and 1 for the threshold to use'
      - name: sections_to_exclude
        in: query
        required: false
        schema:
          items:
            type: string
          type: array
        description: 'Sections to exclude from link suggestion generation. Exact match is used. To exclude the lead section, use %LEAD%'
      - name: max_recommendations
        in: query
        required: false
        type: number
        default: 15
        description: 'Maximum number of recommendations to return'
      responses:
        200:
          description: 'Success: Page found'
          schema:
            $ref: '#/definitions/LinkRecommendationSet'
swagger: '2.0'
